# site headings
name: "My knowledge base."
title: "Knowledge base."
# site settings
locale: "en-GB"
title_separator: " / "
subtitle: "A library of what I learnt."

# theme settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
