# site headings
site.name: "My knowledge base."
site.title: "Knowledge base."
# site settings
site.locale: "en-GB"
site.title_separator: " / "
site.subtitle: "A library of what I learnt."

# theme settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
